blueprint:
  name: Presence-Based Zone Scenes with DND, Luminance, Upstairs Default & Transition (Corrected)
  description: >-
    Controls zone-specific scenes based on presence. Activates a scene when a zone is occupied
    and turns lights off when all zones are clear. Only runs when Do-Not-Disturb is off
    and ambient light is low. Includes a default 'upstairs' scene and smooth transitions.
  domain: automation
  input:
    dnd_mode:
      name: Do-Not-Disturb Mode
      description: When on, presence-based scene changes are paused.
      selector:
        boolean: {}
    luminance_sensor:
      name: Ambient Luminance Sensor
      selector:
        entity:
          domain: sensor
    lux_threshold:
      name: Lux Threshold
      description: Only run scenes when illuminance is below this value (lux).
      default: 50
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: lux
    transition_duration:
      name: Transition Duration (seconds)
      description: Time in seconds to smoothly transition lights when changing scenes.
      default: 2
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: s
    upstairs_presence:
      name: Upstairs Presence Sensor
      selector:
        entity:
          domain: binary_sensor
    scene_upstairs:
      name: Upstairs Default Scene
      selector:
        entity:
          domain: scene
    dining_presence:
      name: Dining Presence Sensor
      selector:
        entity:
          domain: binary_sensor
    scene_dining:
      name: Dining Zone Scene
      selector:
        entity:
          domain: scene
    cooking_presence:
      name: Cooking Presence Sensor
      selector:
        entity:
          domain: binary_sensor
    scene_cooking:
      name: Cooking Zone Scene
      selector:
        entity:
          domain: scene
    living_presence:
      name: Living Room Presence Sensor
      selector:
        entity:
          domain: binary_sensor
    scene_living:
      name: Living Room Zone Scene
      selector:
        entity:
          domain: scene
    stairs_presence:
      name: Stairs Presence Sensor
      selector:
        entity:
          domain: binary_sensor
    scene_stairs:
      name: Stairs Zone Scene
      selector:
        entity:
          domain: scene
    scene_all_off:
      name: All Off Scene
      description: Scene to activate when no presence is detected anywhere.
      selector:
        entity:
          domain: scene

trigger:
  - platform: state
    entity_id:
      - !input upstairs_presence
      - !input dining_presence
      - !input cooking_presence
      - !input living_presence
      - !input stairs_presence
    # Triggering on both 'on' and 'off' ensures the "all off" state is handled
    to:
    from:

condition:
  - condition: template
    value_template: "{{ not dnd_mode }}"
  - condition: numeric_state
    entity_id: !input luminance_sensor
    below: !input lux_threshold

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input dining_presence
            state: 'on'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_dining
            data:
              transition: !input transition_duration
      - conditions:
          - condition: state
            entity_id: !input cooking_presence
            state: 'on'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_cooking
            data:
              transition: !input transition_duration
      - conditions:
          - condition: state
            entity_id: !input living_presence
            state: 'on'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_living
            data:
              transition: !input transition_duration
      - conditions:
          - condition: state
            entity_id: !input stairs_presence
            state: 'on'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_stairs
            data:
              transition: !input transition_duration
      - conditions:
          - condition: state
            entity_id: !input upstairs_presence
            state: 'on'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_upstairs
            data:
              transition: !input transition_duration
    default:
      - service: scene.turn_on
        target:
          entity_id: !input scene_all_off
        data:
          transition: !input transition_duration

mode: restart
