blueprint:
  name: Multi-Layered Presence Scenes with Default and Zone Overrides
  description: >-
    Activates specific scenes based on presence in individual zones.
    When no specific zone is active but general presence is detected, it reverts to a default scene.
    When all presence is gone, it turns the lights off.
    Obeys a Do-Not-Disturb toggle and a luminance sensor.
  domain: automation

  input:
    # --- General Controls ---
    dnd_mode:
      name: Do-Not-Disturb Toggle
      description: Select the input_boolean helper that will pause this automation when 'on'.
      selector:
        entity:
          domain: input_boolean
    luminance_sensor:
      name: Ambient Luminance Sensor
      description: The sensor that measures ambient light.
      selector:
        entity:
          domain: sensor
    lux_threshold:
      name: Lux Threshold
      description: The automation will only run when illuminance is below this value.
      default: 50
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: lux
    transition_duration:
      name: Transition Duration (seconds)
      description: Time in seconds for smooth light transitions.
      default: 2
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: s
    all_off_target:
      name: Lights to Turn Off
      description: The light group, area, or lights to turn off when no presence is detected.
      selector:
        target:
          entity:
            domain: light

    # --- Global/Default Layer ---
    upstairs_presence:
      name: Global Upstairs Presence Sensor
      description: The main sensor that detects if anyone is upstairs. This triggers the default scene.
      selector:
        entity:
          domain: binary_sensor
    scene_upstairs_default:
      name: Upstairs Default Scene
      description: The scene to activate when general presence is detected, but no specific zone is active.
      selector:
        entity:
          domain: scene

    # --- Specific Zone Layers ---
    dining_presence:
      name: Dining Zone Presence Sensor
      selector:
        entity:
          domain: binary_sensor
    scene_dining:
      name: Dining Zone Scene
      selector:
        entity:
          domain: scene
    living_presence:
      name: Living Room Zone Presence Sensor
      selector:
        entity:
          domain: binary_sensor
    scene_living:
      name: Living Room Zone Scene
      selector:
        entity:
          domain: scene
    # To add more zones, copy the two blocks above and change the names (e.g., cooking_presence, scene_cooking).

trigger:
  - platform: state
    entity_id:
      - !input upstairs_presence
      - !input dining_presence
      - !input living_presence
      # If you add more zones in the input section, also add their presence sensors here.
    to:
    from:

condition:
  - condition: state
    entity_id: !input dnd_mode
    state: 'off'
  - condition: numeric_state
    entity_id: !input luminance_sensor
    below: !input lux_threshold

action:
  - choose:
      # --- PRIORITY 1: Check for specific zones first ---
      - conditions:
          - condition: state
            entity_id: !input dining_presence
            state: 'on'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_dining
            data:
              transition: !input transition_duration
      - conditions:
          - condition: state
            entity_id: !input living_presence
            state: 'on'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_living
            data:
              transition: !input transition_duration

      # --- PRIORITY 2: If no specific zone is active, check for global presence ---
      - conditions:
          - condition: state
            entity_id: !input upstairs_presence
            state: 'on'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_upstairs_default
            data:
              transition: !input transition_duration

    # --- DEFAULT ACTION: If no presence is detected anywhere, turn everything off ---
    default:
      - service: light.turn_off
        target: !input all_off_target
        data:
          transition: !input transition_duration

mode: restart
